- name: Install Tools
  apt: name={{ item }} state=latest update_cache=true
  with_items:
    - language-pack-ja
    - build-essential
    - tmux
    - vim
    - htop
    - git-core
    - wget
    - zlib1g-dev
    - libssl-dev
    - libreadline-dev
    - libyaml-dev
    - libxml2-dev
    - libxslt1-dev
    - libffi-dev
    - curl
    - libcurl3
    - libcurl3-gnutls
    - libcurl4-openssl-dev
    - autoconf
    - bison
    - libreadline6-dev
    - libncurses5-dev
    - libgdbm3
    - libgdbm-dev
    - nodejs
